FROM centos:centos7

RUN yum -y upgrade
RUN yum -y install \
      automake \
      curl \
      cmake \
      openssl-devel \
      file \
      gcc \
      gcc-c++ \
      git \
      kernel-devel \
      libtool \
      make \
      patch \
      python \
      python-devel \
      python-setuptools \
      zip \
      unzip \
      wget \
      which

